"""
Model Training — train an XGBoost classifier for funding success prediction.

Logs experiments to MLflow and saves the best model as model.pkl.

Usage:
    python -m app.models.train_model
"""

import os
import logging
import joblib
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

MODEL_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH = os.path.join(MODEL_DIR, "model.pkl")
ARTIFACTS_PATH = os.path.join(MODEL_DIR, "preprocessing_artifacts.pkl")
TRAINING_DATA_PATH = os.path.join(MODEL_DIR, "training_data.csv")


def load_training_data() -> pd.DataFrame:
    """Load the training CSV generated by seed_data.py."""
    if not os.path.exists(TRAINING_DATA_PATH):
        raise FileNotFoundError(
            f"Training data not found at {TRAINING_DATA_PATH}. "
            "Run 'python -m app.scraping.seed_data' first."
        )
    df = pd.read_csv(TRAINING_DATA_PATH)
    logger.info("Loaded training data: %d rows, %d cols", *df.shape)
    return df


def preprocess_for_training(
    df: pd.DataFrame,
) -> tuple[pd.DataFrame, np.ndarray, dict]:
    """
    Prepare features and target for model training.

    Returns (X, y, artifacts) where artifacts contains the fitted
    encoders and scaler needed for inference.
    """
    # --- Encode categoricals ------------------------------------------------
    industry_le = LabelEncoder()
    df["industry_encoded"] = industry_le.fit_transform(df["industry"].astype(str))

    location_le = LabelEncoder()
    df["location_encoded"] = location_le.fit_transform(df["location"].astype(str))

    # --- Select features ----------------------------------------------------
    feature_cols = [
        "industry_encoded",
        "location_encoded",
        "team_size",
        "startup_age",
        "investor_count",
        "previous_funding_rounds",
    ]
    X = df[feature_cols].copy()
    y = df["funding_success"].values

    # --- Scale numerical features -------------------------------------------
    numerical_cols = ["team_size", "startup_age", "investor_count", "previous_funding_rounds"]
    scaler = StandardScaler()
    X[numerical_cols] = scaler.fit_transform(X[numerical_cols])

    artifacts = {
        "industry_encoder": industry_le,
        "location_encoder": location_le,
        "scaler": scaler,
        "feature_cols": feature_cols,
        "numerical_cols": numerical_cols,
    }

    return X, y, artifacts


def train(df: pd.DataFrame | None = None, target_col: str = "funding_success") -> dict:
    """
    Full training pipeline: load → preprocess → split → train → evaluate → save.

    Parameters
    ----------
    df : pd.DataFrame, optional
        Raw dataset. If None, loads from training_data.csv.
    target_col : str
        Name of the binary target column.

    Returns
    -------
    dict
        Evaluation metrics: accuracy, f1_score, roc_auc.
    """
    if df is None:
        df = load_training_data()

    # --- Preprocess ---------------------------------------------------------
    X, y, artifacts = preprocess_for_training(df)

    # --- Split --------------------------------------------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # --- Train ---------------------------------------------------------------
    params = {
        "learning_rate": 0.1,
        "max_depth": 6,
        "n_estimators": 200,
        "eval_metric": "logloss",
        "random_state": 42,
    }
    model = XGBClassifier(**params)

    # Try MLflow logging (graceful fallback if unavailable)
    try:
        import mlflow
        import mlflow.xgboost

        mlflow.set_experiment("startup_funding_prediction")

        with mlflow.start_run(run_name="xgboost_funding_v1"):
            model.fit(X_train, y_train)

            y_pred = model.predict(X_test)
            y_proba = model.predict_proba(X_test)[:, 1]

            metrics = {
                "accuracy": round(accuracy_score(y_test, y_pred), 4),
                "f1_score": round(f1_score(y_test, y_pred), 4),
                "roc_auc": round(roc_auc_score(y_test, y_proba), 4),
            }

            mlflow.log_params(params)
            mlflow.log_metrics(metrics)
            mlflow.xgboost.log_model(model, artifact_path="model")

            logger.info("📊 MLflow run logged successfully.")

    except Exception as e:
        logger.warning("MLflow unavailable (%s). Training without tracking.", e)
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        y_proba = model.predict_proba(X_test)[:, 1]

        metrics = {
            "accuracy": round(accuracy_score(y_test, y_pred), 4),
            "f1_score": round(f1_score(y_test, y_pred), 4),
            "roc_auc": round(roc_auc_score(y_test, y_proba), 4),
        }

    logger.info("✅ Training complete. Metrics: %s", metrics)

    # --- Save model & artifacts to disk -------------------------------------
    joblib.dump(model, MODEL_PATH)
    logger.info("💾 Model saved to %s", MODEL_PATH)

    joblib.dump(artifacts, ARTIFACTS_PATH)
    logger.info("💾 Preprocessing artifacts saved to %s", ARTIFACTS_PATH)

    return metrics


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s | %(message)s",
    )
    results = train()
    print("\n" + "=" * 50)
    print("🎯 MODEL EVALUATION RESULTS")
    print("=" * 50)
    for metric, value in results.items():
        print(f"  {metric:>10}: {value:.4f}")
    print("=" * 50)
